/* This file is autogenerated by CMake, based on the INCODE_EPSG_* options specified during configure.

    Choosing an EPSG CSV file for inclusion into code will run csv/csv2c.py on the file and include the

    resulting c-source as a build target, as opposed to using GDAL_DATA-dir to find the EPSG codes at runtime. */
; 

/* Pointers to csv data included in code */
static const datafile_t files[] = {

  { NULL, NULL }};