// The content of this file is generated with help of update-ids utility Do not edit.

static const char* BUILTIN_TIME_ZONE_VERSION = "2025a";

// Do not change order of items in this array! The index corresponds to a TimeZone ID, which must be fixed!
static const char* BUILTIN_TIME_ZONE_LIST[] = {
	"GMT",	// fb_tzid_gmt - 65535
	"ACT",	// fb_tzid_act - 65534
	"AET",	// fb_tzid_aet - 65533
	"AGT",	// fb_tzid_agt - 65532
	"ART",	// fb_tzid_art - 65531
	"AST",	// fb_tzid_ast - 65530
	"Africa/Abidjan",	// fb_tzid_africa_abidjan - 65529
	"Africa/Accra",	// fb_tzid_africa_accra - 65528
	"Africa/Addis_Ababa",	// fb_tzid_africa_addis_ababa - 65527
	"Africa/Algiers",	// fb_tzid_africa_algiers - 65526
	"Africa/Asmara",	// fb_tzid_africa_asmara - 65525
	"Africa/Asmera",	// fb_tzid_africa_asmera - 65524
	"Africa/Bamako",	// fb_tzid_africa_bamako - 65523
	"Africa/Bangui",	// fb_tzid_africa_bangui - 65522
	"Africa/Banjul",	// fb_tzid_africa_banjul - 65521
	"Africa/Bissau",	// fb_tzid_africa_bissau - 65520
	"Africa/Blantyre",	// fb_tzid_africa_blantyre - 65519
	"Africa/Brazzaville",	// fb_tzid_africa_brazzaville - 65518
	"Africa/Bujumbura",	// fb_tzid_africa_bujumbura - 65517
	"Africa/Cairo",	// fb_tzid_africa_cairo - 65516
	"Africa/Casablanca",	// fb_tzid_africa_casablanca - 65515
	"Africa/Ceuta",	// fb_tzid_africa_ceuta - 65514
	"Africa/Conakry",	// fb_tzid_africa_conakry - 65513
	"Africa/Dakar",	// fb_tzid_africa_dakar - 65512
	"Africa/Dar_es_Salaam",	// fb_tzid_africa_dar_es_salaam - 65511
	"Africa/Djibouti",	// fb_tzid_africa_djibouti - 65510
	"Africa/Douala",	// fb_tzid_africa_douala - 65509
	"Africa/El_Aaiun",	// fb_tzid_africa_el_aaiun - 65508
	"Africa/Freetown",	// fb_tzid_africa_freetown - 65507
	"Africa/Gaborone",	// fb_tzid_africa_gaborone - 65506
	"Africa/Harare",	// fb_tzid_africa_harare - 65505
	"Africa/Johannesburg",	// fb_tzid_africa_johannesburg - 65504
	"Africa/Juba",	// fb_tzid_africa_juba - 65503
	"Africa/Kampala",	// fb_tzid_africa_kampala - 65502
	"Africa/Khartoum",	// fb_tzid_africa_khartoum - 65501
	"Africa/Kigali",	// fb_tzid_africa_kigali - 65500
	"Africa/Kinshasa",	// fb_tzid_africa_kinshasa - 65499
	"Africa/Lagos",	// fb_tzid_africa_lagos - 65498
	"Africa/Libreville",	// fb_tzid_africa_libreville - 65497
	"Africa/Lome",	// fb_tzid_africa_lome - 65496
	"Africa/Luanda",	// fb_tzid_africa_luanda - 65495
	"Africa/Lubumbashi",	// fb_tzid_africa_lubumbashi - 65494
	"Africa/Lusaka",	// fb_tzid_africa_lusaka - 65493
	"Africa/Malabo",	// fb_tzid_africa_malabo - 65492
	"Africa/Maputo",	// fb_tzid_africa_maputo - 65491
	"Africa/Maseru",	// fb_tzid_africa_maseru - 65490
	"Africa/Mbabane",	// fb_tzid_africa_mbabane - 65489
	"Africa/Mogadishu",	// fb_tzid_africa_mogadishu - 65488
	"Africa/Monrovia",	// fb_tzid_africa_monrovia - 65487
	"Africa/Nairobi",	// fb_tzid_africa_nairobi - 65486
	"Africa/Ndjamena",	// fb_tzid_africa_ndjamena - 65485
	"Africa/Niamey",	// fb_tzid_africa_niamey - 65484
	"Africa/Nouakchott",	// fb_tzid_africa_nouakchott - 65483
	"Africa/Ouagadougou",	// fb_tzid_africa_ouagadougou - 65482
	"Africa/Porto-Novo",	// fb_tzid_africa_porto_novo - 65481
	"Africa/Sao_Tome",	// fb_tzid_africa_sao_tome - 65480
	"Africa/Timbuktu",	// fb_tzid_africa_timbuktu - 65479
	"Africa/Tripoli",	// fb_tzid_africa_tripoli - 65478
	"Africa/Tunis",	// fb_tzid_africa_tunis - 65477
	"Africa/Windhoek",	// fb_tzid_africa_windhoek - 65476
	"America/Adak",	// fb_tzid_america_adak - 65475
	"America/Anchorage",	// fb_tzid_america_anchorage - 65474
	"America/Anguilla",	// fb_tzid_america_anguilla - 65473
	"America/Antigua",	// fb_tzid_america_antigua - 65472
	"America/Araguaina",	// fb_tzid_america_araguaina - 65471
	"America/Argentina/Buenos_Aires",	// fb_tzid_america_argentina_buenos_aires - 65470
	"America/Argentina/Catamarca",	// fb_tzid_america_argentina_catamarca - 65469
	"America/Argentina/ComodRivadavia",	// fb_tzid_america_argentina_comodrivadavia - 65468
	"America/Argentina/Cordoba",	// fb_tzid_america_argentina_cordoba - 65467
	"America/Argentina/Jujuy",	// fb_tzid_america_argentina_jujuy - 65466
	"America/Argentina/La_Rioja",	// fb_tzid_america_argentina_la_rioja - 65465
	"America/Argentina/Mendoza",	// fb_tzid_america_argentina_mendoza - 65464
	"America/Argentina/Rio_Gallegos",	// fb_tzid_america_argentina_rio_gallegos - 65463
	"America/Argentina/Salta",	// fb_tzid_america_argentina_salta - 65462
	"America/Argentina/San_Juan",	// fb_tzid_america_argentina_san_juan - 65461
	"America/Argentina/San_Luis",	// fb_tzid_america_argentina_san_luis - 65460
	"America/Argentina/Tucuman",	// fb_tzid_america_argentina_tucuman - 65459
	"America/Argentina/Ushuaia",	// fb_tzid_america_argentina_ushuaia - 65458
	"America/Aruba",	// fb_tzid_america_aruba - 65457
	"America/Asuncion",	// fb_tzid_america_asuncion - 65456
	"America/Atikokan",	// fb_tzid_america_atikokan - 65455
	"America/Atka",	// fb_tzid_america_atka - 65454
	"America/Bahia",	// fb_tzid_america_bahia - 65453
	"America/Bahia_Banderas",	// fb_tzid_america_bahia_banderas - 65452
	"America/Barbados",	// fb_tzid_america_barbados - 65451
	"America/Belem",	// fb_tzid_america_belem - 65450
	"America/Belize",	// fb_tzid_america_belize - 65449
	"America/Blanc-Sablon",	// fb_tzid_america_blanc_sablon - 65448
	"America/Boa_Vista",	// fb_tzid_america_boa_vista - 65447
	"America/Bogota",	// fb_tzid_america_bogota - 65446
	"America/Boise",	// fb_tzid_america_boise - 65445
	"America/Buenos_Aires",	// fb_tzid_america_buenos_aires - 65444
	"America/Cambridge_Bay",	// fb_tzid_america_cambridge_bay - 65443
	"America/Campo_Grande",	// fb_tzid_america_campo_grande - 65442
	"America/Cancun",	// fb_tzid_america_cancun - 65441
	"America/Caracas",	// fb_tzid_america_caracas - 65440
	"America/Catamarca",	// fb_tzid_america_catamarca - 65439
	"America/Cayenne",	// fb_tzid_america_cayenne - 65438
	"America/Cayman",	// fb_tzid_america_cayman - 65437
	"America/Chicago",	// fb_tzid_america_chicago - 65436
	"America/Chihuahua",	// fb_tzid_america_chihuahua - 65435
	"America/Coral_Harbour",	// fb_tzid_america_coral_harbour - 65434
	"America/Cordoba",	// fb_tzid_america_cordoba - 65433
	"America/Costa_Rica",	// fb_tzid_america_costa_rica - 65432
	"America/Creston",	// fb_tzid_america_creston - 65431
	"America/Cuiaba",	// fb_tzid_america_cuiaba - 65430
	"America/Curacao",	// fb_tzid_america_curacao - 65429
	"America/Danmarkshavn",	// fb_tzid_america_danmarkshavn - 65428
	"America/Dawson",	// fb_tzid_america_dawson - 65427
	"America/Dawson_Creek",	// fb_tzid_america_dawson_creek - 65426
	"America/Denver",	// fb_tzid_america_denver - 65425
	"America/Detroit",	// fb_tzid_america_detroit - 65424
	"America/Dominica",	// fb_tzid_america_dominica - 65423
	"America/Edmonton",	// fb_tzid_america_edmonton - 65422
	"America/Eirunepe",	// fb_tzid_america_eirunepe - 65421
	"America/El_Salvador",	// fb_tzid_america_el_salvador - 65420
	"America/Ensenada",	// fb_tzid_america_ensenada - 65419
	"America/Fort_Nelson",	// fb_tzid_america_fort_nelson - 65418
	"America/Fort_Wayne",	// fb_tzid_america_fort_wayne - 65417
	"America/Fortaleza",	// fb_tzid_america_fortaleza - 65416
	"America/Glace_Bay",	// fb_tzid_america_glace_bay - 65415
	"America/Godthab",	// fb_tzid_america_godthab - 65414
	"America/Goose_Bay",	// fb_tzid_america_goose_bay - 65413
	"America/Grand_Turk",	// fb_tzid_america_grand_turk - 65412
	"America/Grenada",	// fb_tzid_america_grenada - 65411
	"America/Guadeloupe",	// fb_tzid_america_guadeloupe - 65410
	"America/Guatemala",	// fb_tzid_america_guatemala - 65409
	"America/Guayaquil",	// fb_tzid_america_guayaquil - 65408
	"America/Guyana",	// fb_tzid_america_guyana - 65407
	"America/Halifax",	// fb_tzid_america_halifax - 65406
	"America/Havana",	// fb_tzid_america_havana - 65405
	"America/Hermosillo",	// fb_tzid_america_hermosillo - 65404
	"America/Indiana/Indianapolis",	// fb_tzid_america_indiana_indianapolis - 65403
	"America/Indiana/Knox",	// fb_tzid_america_indiana_knox - 65402
	"America/Indiana/Marengo",	// fb_tzid_america_indiana_marengo - 65401
	"America/Indiana/Petersburg",	// fb_tzid_america_indiana_petersburg - 65400
	"America/Indiana/Tell_City",	// fb_tzid_america_indiana_tell_city - 65399
	"America/Indiana/Vevay",	// fb_tzid_america_indiana_vevay - 65398
	"America/Indiana/Vincennes",	// fb_tzid_america_indiana_vincennes - 65397
	"America/Indiana/Winamac",	// fb_tzid_america_indiana_winamac - 65396
	"America/Indianapolis",	// fb_tzid_america_indianapolis - 65395
	"America/Inuvik",	// fb_tzid_america_inuvik - 65394
	"America/Iqaluit",	// fb_tzid_america_iqaluit - 65393
	"America/Jamaica",	// fb_tzid_america_jamaica - 65392
	"America/Jujuy",	// fb_tzid_america_jujuy - 65391
	"America/Juneau",	// fb_tzid_america_juneau - 65390
	"America/Kentucky/Louisville",	// fb_tzid_america_kentucky_louisville - 65389
	"America/Kentucky/Monticello",	// fb_tzid_america_kentucky_monticello - 65388
	"America/Knox_IN",	// fb_tzid_america_knox_in - 65387
	"America/Kralendijk",	// fb_tzid_america_kralendijk - 65386
	"America/La_Paz",	// fb_tzid_america_la_paz - 65385
	"America/Lima",	// fb_tzid_america_lima - 65384
	"America/Los_Angeles",	// fb_tzid_america_los_angeles - 65383
	"America/Louisville",	// fb_tzid_america_louisville - 65382
	"America/Lower_Princes",	// fb_tzid_america_lower_princes - 65381
	"America/Maceio",	// fb_tzid_america_maceio - 65380
	"America/Managua",	// fb_tzid_america_managua - 65379
	"America/Manaus",	// fb_tzid_america_manaus - 65378
	"America/Marigot",	// fb_tzid_america_marigot - 65377
	"America/Martinique",	// fb_tzid_america_martinique - 65376
	"America/Matamoros",	// fb_tzid_america_matamoros - 65375
	"America/Mazatlan",	// fb_tzid_america_mazatlan - 65374
	"America/Mendoza",	// fb_tzid_america_mendoza - 65373
	"America/Menominee",	// fb_tzid_america_menominee - 65372
	"America/Merida",	// fb_tzid_america_merida - 65371
	"America/Metlakatla",	// fb_tzid_america_metlakatla - 65370
	"America/Mexico_City",	// fb_tzid_america_mexico_city - 65369
	"America/Miquelon",	// fb_tzid_america_miquelon - 65368
	"America/Moncton",	// fb_tzid_america_moncton - 65367
	"America/Monterrey",	// fb_tzid_america_monterrey - 65366
	"America/Montevideo",	// fb_tzid_america_montevideo - 65365
	"America/Montreal",	// fb_tzid_america_montreal - 65364
	"America/Montserrat",	// fb_tzid_america_montserrat - 65363
	"America/Nassau",	// fb_tzid_america_nassau - 65362
	"America/New_York",	// fb_tzid_america_new_york - 65361
	"America/Nipigon",	// fb_tzid_america_nipigon - 65360
	"America/Nome",	// fb_tzid_america_nome - 65359
	"America/Noronha",	// fb_tzid_america_noronha - 65358
	"America/North_Dakota/Beulah",	// fb_tzid_america_north_dakota_beulah - 65357
	"America/North_Dakota/Center",	// fb_tzid_america_north_dakota_center - 65356
	"America/North_Dakota/New_Salem",	// fb_tzid_america_north_dakota_new_salem - 65355
	"America/Ojinaga",	// fb_tzid_america_ojinaga - 65354
	"America/Panama",	// fb_tzid_america_panama - 65353
	"America/Pangnirtung",	// fb_tzid_america_pangnirtung - 65352
	"America/Paramaribo",	// fb_tzid_america_paramaribo - 65351
	"America/Phoenix",	// fb_tzid_america_phoenix - 65350
	"America/Port-au-Prince",	// fb_tzid_america_port_au_prince - 65349
	"America/Port_of_Spain",	// fb_tzid_america_port_of_spain - 65348
	"America/Porto_Acre",	// fb_tzid_america_porto_acre - 65347
	"America/Porto_Velho",	// fb_tzid_america_porto_velho - 65346
	"America/Puerto_Rico",	// fb_tzid_america_puerto_rico - 65345
	"America/Punta_Arenas",	// fb_tzid_america_punta_arenas - 65344
	"America/Rainy_River",	// fb_tzid_america_rainy_river - 65343
	"America/Rankin_Inlet",	// fb_tzid_america_rankin_inlet - 65342
	"America/Recife",	// fb_tzid_america_recife - 65341
	"America/Regina",	// fb_tzid_america_regina - 65340
	"America/Resolute",	// fb_tzid_america_resolute - 65339
	"America/Rio_Branco",	// fb_tzid_america_rio_branco - 65338
	"America/Rosario",	// fb_tzid_america_rosario - 65337
	"America/Santa_Isabel",	// fb_tzid_america_santa_isabel - 65336
	"America/Santarem",	// fb_tzid_america_santarem - 65335
	"America/Santiago",	// fb_tzid_america_santiago - 65334
	"America/Santo_Domingo",	// fb_tzid_america_santo_domingo - 65333
	"America/Sao_Paulo",	// fb_tzid_america_sao_paulo - 65332
	"America/Scoresbysund",	// fb_tzid_america_scoresbysund - 65331
	"America/Shiprock",	// fb_tzid_america_shiprock - 65330
	"America/Sitka",	// fb_tzid_america_sitka - 65329
	"America/St_Barthelemy",	// fb_tzid_america_st_barthelemy - 65328
	"America/St_Johns",	// fb_tzid_america_st_johns - 65327
	"America/St_Kitts",	// fb_tzid_america_st_kitts - 65326
	"America/St_Lucia",	// fb_tzid_america_st_lucia - 65325
	"America/St_Thomas",	// fb_tzid_america_st_thomas - 65324
	"America/St_Vincent",	// fb_tzid_america_st_vincent - 65323
	"America/Swift_Current",	// fb_tzid_america_swift_current - 65322
	"America/Tegucigalpa",	// fb_tzid_america_tegucigalpa - 65321
	"America/Thule",	// fb_tzid_america_thule - 65320
	"America/Thunder_Bay",	// fb_tzid_america_thunder_bay - 65319
	"America/Tijuana",	// fb_tzid_america_tijuana - 65318
	"America/Toronto",	// fb_tzid_america_toronto - 65317
	"America/Tortola",	// fb_tzid_america_tortola - 65316
	"America/Vancouver",	// fb_tzid_america_vancouver - 65315
	"America/Virgin",	// fb_tzid_america_virgin - 65314
	"America/Whitehorse",	// fb_tzid_america_whitehorse - 65313
	"America/Winnipeg",	// fb_tzid_america_winnipeg - 65312
	"America/Yakutat",	// fb_tzid_america_yakutat - 65311
	"America/Yellowknife",	// fb_tzid_america_yellowknife - 65310
	"Antarctica/Casey",	// fb_tzid_antarctica_casey - 65309
	"Antarctica/Davis",	// fb_tzid_antarctica_davis - 65308
	"Antarctica/DumontDUrville",	// fb_tzid_antarctica_dumontdurville - 65307
	"Antarctica/Macquarie",	// fb_tzid_antarctica_macquarie - 65306
	"Antarctica/Mawson",	// fb_tzid_antarctica_mawson - 65305
	"Antarctica/McMurdo",	// fb_tzid_antarctica_mcmurdo - 65304
	"Antarctica/Palmer",	// fb_tzid_antarctica_palmer - 65303
	"Antarctica/Rothera",	// fb_tzid_antarctica_rothera - 65302
	"Antarctica/South_Pole",	// fb_tzid_antarctica_south_pole - 65301
	"Antarctica/Syowa",	// fb_tzid_antarctica_syowa - 65300
	"Antarctica/Troll",	// fb_tzid_antarctica_troll - 65299
	"Antarctica/Vostok",	// fb_tzid_antarctica_vostok - 65298
	"Arctic/Longyearbyen",	// fb_tzid_arctic_longyearbyen - 65297
	"Asia/Aden",	// fb_tzid_asia_aden - 65296
	"Asia/Almaty",	// fb_tzid_asia_almaty - 65295
	"Asia/Amman",	// fb_tzid_asia_amman - 65294
	"Asia/Anadyr",	// fb_tzid_asia_anadyr - 65293
	"Asia/Aqtau",	// fb_tzid_asia_aqtau - 65292
	"Asia/Aqtobe",	// fb_tzid_asia_aqtobe - 65291
	"Asia/Ashgabat",	// fb_tzid_asia_ashgabat - 65290
	"Asia/Ashkhabad",	// fb_tzid_asia_ashkhabad - 65289
	"Asia/Atyrau",	// fb_tzid_asia_atyrau - 65288
	"Asia/Baghdad",	// fb_tzid_asia_baghdad - 65287
	"Asia/Bahrain",	// fb_tzid_asia_bahrain - 65286
	"Asia/Baku",	// fb_tzid_asia_baku - 65285
	"Asia/Bangkok",	// fb_tzid_asia_bangkok - 65284
	"Asia/Barnaul",	// fb_tzid_asia_barnaul - 65283
	"Asia/Beirut",	// fb_tzid_asia_beirut - 65282
	"Asia/Bishkek",	// fb_tzid_asia_bishkek - 65281
	"Asia/Brunei",	// fb_tzid_asia_brunei - 65280
	"Asia/Calcutta",	// fb_tzid_asia_calcutta - 65279
	"Asia/Chita",	// fb_tzid_asia_chita - 65278
	"Asia/Choibalsan",	// fb_tzid_asia_choibalsan - 65277
	"Asia/Chongqing",	// fb_tzid_asia_chongqing - 65276
	"Asia/Chungking",	// fb_tzid_asia_chungking - 65275
	"Asia/Colombo",	// fb_tzid_asia_colombo - 65274
	"Asia/Dacca",	// fb_tzid_asia_dacca - 65273
	"Asia/Damascus",	// fb_tzid_asia_damascus - 65272
	"Asia/Dhaka",	// fb_tzid_asia_dhaka - 65271
	"Asia/Dili",	// fb_tzid_asia_dili - 65270
	"Asia/Dubai",	// fb_tzid_asia_dubai - 65269
	"Asia/Dushanbe",	// fb_tzid_asia_dushanbe - 65268
	"Asia/Famagusta",	// fb_tzid_asia_famagusta - 65267
	"Asia/Gaza",	// fb_tzid_asia_gaza - 65266
	"Asia/Harbin",	// fb_tzid_asia_harbin - 65265
	"Asia/Hebron",	// fb_tzid_asia_hebron - 65264
	"Asia/Ho_Chi_Minh",	// fb_tzid_asia_ho_chi_minh - 65263
	"Asia/Hong_Kong",	// fb_tzid_asia_hong_kong - 65262
	"Asia/Hovd",	// fb_tzid_asia_hovd - 65261
	"Asia/Irkutsk",	// fb_tzid_asia_irkutsk - 65260
	"Asia/Istanbul",	// fb_tzid_asia_istanbul - 65259
	"Asia/Jakarta",	// fb_tzid_asia_jakarta - 65258
	"Asia/Jayapura",	// fb_tzid_asia_jayapura - 65257
	"Asia/Jerusalem",	// fb_tzid_asia_jerusalem - 65256
	"Asia/Kabul",	// fb_tzid_asia_kabul - 65255
	"Asia/Kamchatka",	// fb_tzid_asia_kamchatka - 65254
	"Asia/Karachi",	// fb_tzid_asia_karachi - 65253
	"Asia/Kashgar",	// fb_tzid_asia_kashgar - 65252
	"Asia/Kathmandu",	// fb_tzid_asia_kathmandu - 65251
	"Asia/Katmandu",	// fb_tzid_asia_katmandu - 65250
	"Asia/Khandyga",	// fb_tzid_asia_khandyga - 65249
	"Asia/Kolkata",	// fb_tzid_asia_kolkata - 65248
	"Asia/Krasnoyarsk",	// fb_tzid_asia_krasnoyarsk - 65247
	"Asia/Kuala_Lumpur",	// fb_tzid_asia_kuala_lumpur - 65246
	"Asia/Kuching",	// fb_tzid_asia_kuching - 65245
	"Asia/Kuwait",	// fb_tzid_asia_kuwait - 65244
	"Asia/Macao",	// fb_tzid_asia_macao - 65243
	"Asia/Macau",	// fb_tzid_asia_macau - 65242
	"Asia/Magadan",	// fb_tzid_asia_magadan - 65241
	"Asia/Makassar",	// fb_tzid_asia_makassar - 65240
	"Asia/Manila",	// fb_tzid_asia_manila - 65239
	"Asia/Muscat",	// fb_tzid_asia_muscat - 65238
	"Asia/Nicosia",	// fb_tzid_asia_nicosia - 65237
	"Asia/Novokuznetsk",	// fb_tzid_asia_novokuznetsk - 65236
	"Asia/Novosibirsk",	// fb_tzid_asia_novosibirsk - 65235
	"Asia/Omsk",	// fb_tzid_asia_omsk - 65234
	"Asia/Oral",	// fb_tzid_asia_oral - 65233
	"Asia/Phnom_Penh",	// fb_tzid_asia_phnom_penh - 65232
	"Asia/Pontianak",	// fb_tzid_asia_pontianak - 65231
	"Asia/Pyongyang",	// fb_tzid_asia_pyongyang - 65230
	"Asia/Qatar",	// fb_tzid_asia_qatar - 65229
	"Asia/Qyzylorda",	// fb_tzid_asia_qyzylorda - 65228
	"Asia/Rangoon",	// fb_tzid_asia_rangoon - 65227
	"Asia/Riyadh",	// fb_tzid_asia_riyadh - 65226
	"Asia/Saigon",	// fb_tzid_asia_saigon - 65225
	"Asia/Sakhalin",	// fb_tzid_asia_sakhalin - 65224
	"Asia/Samarkand",	// fb_tzid_asia_samarkand - 65223
	"Asia/Seoul",	// fb_tzid_asia_seoul - 65222
	"Asia/Shanghai",	// fb_tzid_asia_shanghai - 65221
	"Asia/Singapore",	// fb_tzid_asia_singapore - 65220
	"Asia/Srednekolymsk",	// fb_tzid_asia_srednekolymsk - 65219
	"Asia/Taipei",	// fb_tzid_asia_taipei - 65218
	"Asia/Tashkent",	// fb_tzid_asia_tashkent - 65217
	"Asia/Tbilisi",	// fb_tzid_asia_tbilisi - 65216
	"Asia/Tehran",	// fb_tzid_asia_tehran - 65215
	"Asia/Tel_Aviv",	// fb_tzid_asia_tel_aviv - 65214
	"Asia/Thimbu",	// fb_tzid_asia_thimbu - 65213
	"Asia/Thimphu",	// fb_tzid_asia_thimphu - 65212
	"Asia/Tokyo",	// fb_tzid_asia_tokyo - 65211
	"Asia/Tomsk",	// fb_tzid_asia_tomsk - 65210
	"Asia/Ujung_Pandang",	// fb_tzid_asia_ujung_pandang - 65209
	"Asia/Ulaanbaatar",	// fb_tzid_asia_ulaanbaatar - 65208
	"Asia/Ulan_Bator",	// fb_tzid_asia_ulan_bator - 65207
	"Asia/Urumqi",	// fb_tzid_asia_urumqi - 65206
	"Asia/Ust-Nera",	// fb_tzid_asia_ust_nera - 65205
	"Asia/Vientiane",	// fb_tzid_asia_vientiane - 65204
	"Asia/Vladivostok",	// fb_tzid_asia_vladivostok - 65203
	"Asia/Yakutsk",	// fb_tzid_asia_yakutsk - 65202
	"Asia/Yangon",	// fb_tzid_asia_yangon - 65201
	"Asia/Yekaterinburg",	// fb_tzid_asia_yekaterinburg - 65200
	"Asia/Yerevan",	// fb_tzid_asia_yerevan - 65199
	"Atlantic/Azores",	// fb_tzid_atlantic_azores - 65198
	"Atlantic/Bermuda",	// fb_tzid_atlantic_bermuda - 65197
	"Atlantic/Canary",	// fb_tzid_atlantic_canary - 65196
	"Atlantic/Cape_Verde",	// fb_tzid_atlantic_cape_verde - 65195
	"Atlantic/Faeroe",	// fb_tzid_atlantic_faeroe - 65194
	"Atlantic/Faroe",	// fb_tzid_atlantic_faroe - 65193
	"Atlantic/Jan_Mayen",	// fb_tzid_atlantic_jan_mayen - 65192
	"Atlantic/Madeira",	// fb_tzid_atlantic_madeira - 65191
	"Atlantic/Reykjavik",	// fb_tzid_atlantic_reykjavik - 65190
	"Atlantic/South_Georgia",	// fb_tzid_atlantic_south_georgia - 65189
	"Atlantic/St_Helena",	// fb_tzid_atlantic_st_helena - 65188
	"Atlantic/Stanley",	// fb_tzid_atlantic_stanley - 65187
	"Australia/ACT",	// fb_tzid_australia_act - 65186
	"Australia/Adelaide",	// fb_tzid_australia_adelaide - 65185
	"Australia/Brisbane",	// fb_tzid_australia_brisbane - 65184
	"Australia/Broken_Hill",	// fb_tzid_australia_broken_hill - 65183
	"Australia/Canberra",	// fb_tzid_australia_canberra - 65182
	"Australia/Currie",	// fb_tzid_australia_currie - 65181
	"Australia/Darwin",	// fb_tzid_australia_darwin - 65180
	"Australia/Eucla",	// fb_tzid_australia_eucla - 65179
	"Australia/Hobart",	// fb_tzid_australia_hobart - 65178
	"Australia/LHI",	// fb_tzid_australia_lhi - 65177
	"Australia/Lindeman",	// fb_tzid_australia_lindeman - 65176
	"Australia/Lord_Howe",	// fb_tzid_australia_lord_howe - 65175
	"Australia/Melbourne",	// fb_tzid_australia_melbourne - 65174
	"Australia/NSW",	// fb_tzid_australia_nsw - 65173
	"Australia/North",	// fb_tzid_australia_north - 65172
	"Australia/Perth",	// fb_tzid_australia_perth - 65171
	"Australia/Queensland",	// fb_tzid_australia_queensland - 65170
	"Australia/South",	// fb_tzid_australia_south - 65169
	"Australia/Sydney",	// fb_tzid_australia_sydney - 65168
	"Australia/Tasmania",	// fb_tzid_australia_tasmania - 65167
	"Australia/Victoria",	// fb_tzid_australia_victoria - 65166
	"Australia/West",	// fb_tzid_australia_west - 65165
	"Australia/Yancowinna",	// fb_tzid_australia_yancowinna - 65164
	"BET",	// fb_tzid_bet - 65163
	"BST",	// fb_tzid_bst - 65162
	"Brazil/Acre",	// fb_tzid_brazil_acre - 65161
	"Brazil/DeNoronha",	// fb_tzid_brazil_denoronha - 65160
	"Brazil/East",	// fb_tzid_brazil_east - 65159
	"Brazil/West",	// fb_tzid_brazil_west - 65158
	"CAT",	// fb_tzid_cat - 65157
	"CET",	// fb_tzid_cet - 65156
	"CNT",	// fb_tzid_cnt - 65155
	"CST",	// fb_tzid_cst - 65154
	"CST6CDT",	// fb_tzid_cst6cdt - 65153
	"CTT",	// fb_tzid_ctt - 65152
	"Canada/Atlantic",	// fb_tzid_canada_atlantic - 65151
	"Canada/Central",	// fb_tzid_canada_central - 65150
	"Canada/East-Saskatchewan",	// fb_tzid_canada_east_saskatchewan - 65149
	"Canada/Eastern",	// fb_tzid_canada_eastern - 65148
	"Canada/Mountain",	// fb_tzid_canada_mountain - 65147
	"Canada/Newfoundland",	// fb_tzid_canada_newfoundland - 65146
	"Canada/Pacific",	// fb_tzid_canada_pacific - 65145
	"Canada/Saskatchewan",	// fb_tzid_canada_saskatchewan - 65144
	"Canada/Yukon",	// fb_tzid_canada_yukon - 65143
	"Chile/Continental",	// fb_tzid_chile_continental - 65142
	"Chile/EasterIsland",	// fb_tzid_chile_easterisland - 65141
	"Cuba",	// fb_tzid_cuba - 65140
	"EAT",	// fb_tzid_eat - 65139
	"ECT",	// fb_tzid_ect - 65138
	"EET",	// fb_tzid_eet - 65137
	"EST",	// fb_tzid_est - 65136
	"EST5EDT",	// fb_tzid_est5edt - 65135
	"Egypt",	// fb_tzid_egypt - 65134
	"Eire",	// fb_tzid_eire - 65133
	"Etc/GMT",	// fb_tzid_etc_gmt - 65132
	"Etc/GMT+0",	// fb_tzid_etc_gmt_plus_0 - 65131
	"Etc/GMT+1",	// fb_tzid_etc_gmt_plus_1 - 65130
	"Etc/GMT+10",	// fb_tzid_etc_gmt_plus_10 - 65129
	"Etc/GMT+11",	// fb_tzid_etc_gmt_plus_11 - 65128
	"Etc/GMT+12",	// fb_tzid_etc_gmt_plus_12 - 65127
	"Etc/GMT+2",	// fb_tzid_etc_gmt_plus_2 - 65126
	"Etc/GMT+3",	// fb_tzid_etc_gmt_plus_3 - 65125
	"Etc/GMT+4",	// fb_tzid_etc_gmt_plus_4 - 65124
	"Etc/GMT+5",	// fb_tzid_etc_gmt_plus_5 - 65123
	"Etc/GMT+6",	// fb_tzid_etc_gmt_plus_6 - 65122
	"Etc/GMT+7",	// fb_tzid_etc_gmt_plus_7 - 65121
	"Etc/GMT+8",	// fb_tzid_etc_gmt_plus_8 - 65120
	"Etc/GMT+9",	// fb_tzid_etc_gmt_plus_9 - 65119
	"Etc/GMT-0",	// fb_tzid_etc_gmt_minus_0 - 65118
	"Etc/GMT-1",	// fb_tzid_etc_gmt_minus_1 - 65117
	"Etc/GMT-10",	// fb_tzid_etc_gmt_minus_10 - 65116
	"Etc/GMT-11",	// fb_tzid_etc_gmt_minus_11 - 65115
	"Etc/GMT-12",	// fb_tzid_etc_gmt_minus_12 - 65114
	"Etc/GMT-13",	// fb_tzid_etc_gmt_minus_13 - 65113
	"Etc/GMT-14",	// fb_tzid_etc_gmt_minus_14 - 65112
	"Etc/GMT-2",	// fb_tzid_etc_gmt_minus_2 - 65111
	"Etc/GMT-3",	// fb_tzid_etc_gmt_minus_3 - 65110
	"Etc/GMT-4",	// fb_tzid_etc_gmt_minus_4 - 65109
	"Etc/GMT-5",	// fb_tzid_etc_gmt_minus_5 - 65108
	"Etc/GMT-6",	// fb_tzid_etc_gmt_minus_6 - 65107
	"Etc/GMT-7",	// fb_tzid_etc_gmt_minus_7 - 65106
	"Etc/GMT-8",	// fb_tzid_etc_gmt_minus_8 - 65105
	"Etc/GMT-9",	// fb_tzid_etc_gmt_minus_9 - 65104
	"Etc/GMT0",	// fb_tzid_etc_gmt0 - 65103
	"Etc/Greenwich",	// fb_tzid_etc_greenwich - 65102
	"Etc/UCT",	// fb_tzid_etc_uct - 65101
	"Etc/UTC",	// fb_tzid_etc_utc - 65100
	"Etc/Universal",	// fb_tzid_etc_universal - 65099
	"Etc/Zulu",	// fb_tzid_etc_zulu - 65098
	"Europe/Amsterdam",	// fb_tzid_europe_amsterdam - 65097
	"Europe/Andorra",	// fb_tzid_europe_andorra - 65096
	"Europe/Astrakhan",	// fb_tzid_europe_astrakhan - 65095
	"Europe/Athens",	// fb_tzid_europe_athens - 65094
	"Europe/Belfast",	// fb_tzid_europe_belfast - 65093
	"Europe/Belgrade",	// fb_tzid_europe_belgrade - 65092
	"Europe/Berlin",	// fb_tzid_europe_berlin - 65091
	"Europe/Bratislava",	// fb_tzid_europe_bratislava - 65090
	"Europe/Brussels",	// fb_tzid_europe_brussels - 65089
	"Europe/Bucharest",	// fb_tzid_europe_bucharest - 65088
	"Europe/Budapest",	// fb_tzid_europe_budapest - 65087
	"Europe/Busingen",	// fb_tzid_europe_busingen - 65086
	"Europe/Chisinau",	// fb_tzid_europe_chisinau - 65085
	"Europe/Copenhagen",	// fb_tzid_europe_copenhagen - 65084
	"Europe/Dublin",	// fb_tzid_europe_dublin - 65083
	"Europe/Gibraltar",	// fb_tzid_europe_gibraltar - 65082
	"Europe/Guernsey",	// fb_tzid_europe_guernsey - 65081
	"Europe/Helsinki",	// fb_tzid_europe_helsinki - 65080
	"Europe/Isle_of_Man",	// fb_tzid_europe_isle_of_man - 65079
	"Europe/Istanbul",	// fb_tzid_europe_istanbul - 65078
	"Europe/Jersey",	// fb_tzid_europe_jersey - 65077
	"Europe/Kaliningrad",	// fb_tzid_europe_kaliningrad - 65076
	"Europe/Kiev",	// fb_tzid_europe_kiev - 65075
	"Europe/Kirov",	// fb_tzid_europe_kirov - 65074
	"Europe/Lisbon",	// fb_tzid_europe_lisbon - 65073
	"Europe/Ljubljana",	// fb_tzid_europe_ljubljana - 65072
	"Europe/London",	// fb_tzid_europe_london - 65071
	"Europe/Luxembourg",	// fb_tzid_europe_luxembourg - 65070
	"Europe/Madrid",	// fb_tzid_europe_madrid - 65069
	"Europe/Malta",	// fb_tzid_europe_malta - 65068
	"Europe/Mariehamn",	// fb_tzid_europe_mariehamn - 65067
	"Europe/Minsk",	// fb_tzid_europe_minsk - 65066
	"Europe/Monaco",	// fb_tzid_europe_monaco - 65065
	"Europe/Moscow",	// fb_tzid_europe_moscow - 65064
	"Europe/Nicosia",	// fb_tzid_europe_nicosia - 65063
	"Europe/Oslo",	// fb_tzid_europe_oslo - 65062
	"Europe/Paris",	// fb_tzid_europe_paris - 65061
	"Europe/Podgorica",	// fb_tzid_europe_podgorica - 65060
	"Europe/Prague",	// fb_tzid_europe_prague - 65059
	"Europe/Riga",	// fb_tzid_europe_riga - 65058
	"Europe/Rome",	// fb_tzid_europe_rome - 65057
	"Europe/Samara",	// fb_tzid_europe_samara - 65056
	"Europe/San_Marino",	// fb_tzid_europe_san_marino - 65055
	"Europe/Sarajevo",	// fb_tzid_europe_sarajevo - 65054
	"Europe/Saratov",	// fb_tzid_europe_saratov - 65053
	"Europe/Simferopol",	// fb_tzid_europe_simferopol - 65052
	"Europe/Skopje",	// fb_tzid_europe_skopje - 65051
	"Europe/Sofia",	// fb_tzid_europe_sofia - 65050
	"Europe/Stockholm",	// fb_tzid_europe_stockholm - 65049
	"Europe/Tallinn",	// fb_tzid_europe_tallinn - 65048
	"Europe/Tirane",	// fb_tzid_europe_tirane - 65047
	"Europe/Tiraspol",	// fb_tzid_europe_tiraspol - 65046
	"Europe/Ulyanovsk",	// fb_tzid_europe_ulyanovsk - 65045
	"Europe/Uzhgorod",	// fb_tzid_europe_uzhgorod - 65044
	"Europe/Vaduz",	// fb_tzid_europe_vaduz - 65043
	"Europe/Vatican",	// fb_tzid_europe_vatican - 65042
	"Europe/Vienna",	// fb_tzid_europe_vienna - 65041
	"Europe/Vilnius",	// fb_tzid_europe_vilnius - 65040
	"Europe/Volgograd",	// fb_tzid_europe_volgograd - 65039
	"Europe/Warsaw",	// fb_tzid_europe_warsaw - 65038
	"Europe/Zagreb",	// fb_tzid_europe_zagreb - 65037
	"Europe/Zaporozhye",	// fb_tzid_europe_zaporozhye - 65036
	"Europe/Zurich",	// fb_tzid_europe_zurich - 65035
	"Factory",	// fb_tzid_factory - 65034
	"GB",	// fb_tzid_gb - 65033
	"GB-Eire",	// fb_tzid_gb_eire - 65032
	"GMT+0",	// fb_tzid_gmt_plus_0 - 65031
	"GMT-0",	// fb_tzid_gmt_minus_0 - 65030
	"GMT0",	// fb_tzid_gmt0 - 65029
	"Greenwich",	// fb_tzid_greenwich - 65028
	"HST",	// fb_tzid_hst - 65027
	"Hongkong",	// fb_tzid_hongkong - 65026
	"IET",	// fb_tzid_iet - 65025
	"IST",	// fb_tzid_ist - 65024
	"Iceland",	// fb_tzid_iceland - 65023
	"Indian/Antananarivo",	// fb_tzid_indian_antananarivo - 65022
	"Indian/Chagos",	// fb_tzid_indian_chagos - 65021
	"Indian/Christmas",	// fb_tzid_indian_christmas - 65020
	"Indian/Cocos",	// fb_tzid_indian_cocos - 65019
	"Indian/Comoro",	// fb_tzid_indian_comoro - 65018
	"Indian/Kerguelen",	// fb_tzid_indian_kerguelen - 65017
	"Indian/Mahe",	// fb_tzid_indian_mahe - 65016
	"Indian/Maldives",	// fb_tzid_indian_maldives - 65015
	"Indian/Mauritius",	// fb_tzid_indian_mauritius - 65014
	"Indian/Mayotte",	// fb_tzid_indian_mayotte - 65013
	"Indian/Reunion",	// fb_tzid_indian_reunion - 65012
	"Iran",	// fb_tzid_iran - 65011
	"Israel",	// fb_tzid_israel - 65010
	"JST",	// fb_tzid_jst - 65009
	"Jamaica",	// fb_tzid_jamaica - 65008
	"Japan",	// fb_tzid_japan - 65007
	"Kwajalein",	// fb_tzid_kwajalein - 65006
	"Libya",	// fb_tzid_libya - 65005
	"MET",	// fb_tzid_met - 65004
	"MIT",	// fb_tzid_mit - 65003
	"MST",	// fb_tzid_mst - 65002
	"MST7MDT",	// fb_tzid_mst7mdt - 65001
	"Mexico/BajaNorte",	// fb_tzid_mexico_bajanorte - 65000
	"Mexico/BajaSur",	// fb_tzid_mexico_bajasur - 64999
	"Mexico/General",	// fb_tzid_mexico_general - 64998
	"NET",	// fb_tzid_net - 64997
	"NST",	// fb_tzid_nst - 64996
	"NZ",	// fb_tzid_nz - 64995
	"NZ-CHAT",	// fb_tzid_nz_chat - 64994
	"Navajo",	// fb_tzid_navajo - 64993
	"PLT",	// fb_tzid_plt - 64992
	"PNT",	// fb_tzid_pnt - 64991
	"PRC",	// fb_tzid_prc - 64990
	"PRT",	// fb_tzid_prt - 64989
	"PST",	// fb_tzid_pst - 64988
	"PST8PDT",	// fb_tzid_pst8pdt - 64987
	"Pacific/Apia",	// fb_tzid_pacific_apia - 64986
	"Pacific/Auckland",	// fb_tzid_pacific_auckland - 64985
	"Pacific/Bougainville",	// fb_tzid_pacific_bougainville - 64984
	"Pacific/Chatham",	// fb_tzid_pacific_chatham - 64983
	"Pacific/Chuuk",	// fb_tzid_pacific_chuuk - 64982
	"Pacific/Easter",	// fb_tzid_pacific_easter - 64981
	"Pacific/Efate",	// fb_tzid_pacific_efate - 64980
	"Pacific/Enderbury",	// fb_tzid_pacific_enderbury - 64979
	"Pacific/Fakaofo",	// fb_tzid_pacific_fakaofo - 64978
	"Pacific/Fiji",	// fb_tzid_pacific_fiji - 64977
	"Pacific/Funafuti",	// fb_tzid_pacific_funafuti - 64976
	"Pacific/Galapagos",	// fb_tzid_pacific_galapagos - 64975
	"Pacific/Gambier",	// fb_tzid_pacific_gambier - 64974
	"Pacific/Guadalcanal",	// fb_tzid_pacific_guadalcanal - 64973
	"Pacific/Guam",	// fb_tzid_pacific_guam - 64972
	"Pacific/Honolulu",	// fb_tzid_pacific_honolulu - 64971
	"Pacific/Johnston",	// fb_tzid_pacific_johnston - 64970
	"Pacific/Kiritimati",	// fb_tzid_pacific_kiritimati - 64969
	"Pacific/Kosrae",	// fb_tzid_pacific_kosrae - 64968
	"Pacific/Kwajalein",	// fb_tzid_pacific_kwajalein - 64967
	"Pacific/Majuro",	// fb_tzid_pacific_majuro - 64966
	"Pacific/Marquesas",	// fb_tzid_pacific_marquesas - 64965
	"Pacific/Midway",	// fb_tzid_pacific_midway - 64964
	"Pacific/Nauru",	// fb_tzid_pacific_nauru - 64963
	"Pacific/Niue",	// fb_tzid_pacific_niue - 64962
	"Pacific/Norfolk",	// fb_tzid_pacific_norfolk - 64961
	"Pacific/Noumea",	// fb_tzid_pacific_noumea - 64960
	"Pacific/Pago_Pago",	// fb_tzid_pacific_pago_pago - 64959
	"Pacific/Palau",	// fb_tzid_pacific_palau - 64958
	"Pacific/Pitcairn",	// fb_tzid_pacific_pitcairn - 64957
	"Pacific/Pohnpei",	// fb_tzid_pacific_pohnpei - 64956
	"Pacific/Ponape",	// fb_tzid_pacific_ponape - 64955
	"Pacific/Port_Moresby",	// fb_tzid_pacific_port_moresby - 64954
	"Pacific/Rarotonga",	// fb_tzid_pacific_rarotonga - 64953
	"Pacific/Saipan",	// fb_tzid_pacific_saipan - 64952
	"Pacific/Samoa",	// fb_tzid_pacific_samoa - 64951
	"Pacific/Tahiti",	// fb_tzid_pacific_tahiti - 64950
	"Pacific/Tarawa",	// fb_tzid_pacific_tarawa - 64949
	"Pacific/Tongatapu",	// fb_tzid_pacific_tongatapu - 64948
	"Pacific/Truk",	// fb_tzid_pacific_truk - 64947
	"Pacific/Wake",	// fb_tzid_pacific_wake - 64946
	"Pacific/Wallis",	// fb_tzid_pacific_wallis - 64945
	"Pacific/Yap",	// fb_tzid_pacific_yap - 64944
	"Poland",	// fb_tzid_poland - 64943
	"Portugal",	// fb_tzid_portugal - 64942
	"ROC",	// fb_tzid_roc - 64941
	"ROK",	// fb_tzid_rok - 64940
	"SST",	// fb_tzid_sst - 64939
	"Singapore",	// fb_tzid_singapore - 64938
	"SystemV/AST4",	// fb_tzid_systemv_ast4 - 64937
	"SystemV/AST4ADT",	// fb_tzid_systemv_ast4adt - 64936
	"SystemV/CST6",	// fb_tzid_systemv_cst6 - 64935
	"SystemV/CST6CDT",	// fb_tzid_systemv_cst6cdt - 64934
	"SystemV/EST5",	// fb_tzid_systemv_est5 - 64933
	"SystemV/EST5EDT",	// fb_tzid_systemv_est5edt - 64932
	"SystemV/HST10",	// fb_tzid_systemv_hst10 - 64931
	"SystemV/MST7",	// fb_tzid_systemv_mst7 - 64930
	"SystemV/MST7MDT",	// fb_tzid_systemv_mst7mdt - 64929
	"SystemV/PST8",	// fb_tzid_systemv_pst8 - 64928
	"SystemV/PST8PDT",	// fb_tzid_systemv_pst8pdt - 64927
	"SystemV/YST9",	// fb_tzid_systemv_yst9 - 64926
	"SystemV/YST9YDT",	// fb_tzid_systemv_yst9ydt - 64925
	"Turkey",	// fb_tzid_turkey - 64924
	"UCT",	// fb_tzid_uct - 64923
	"US/Alaska",	// fb_tzid_us_alaska - 64922
	"US/Aleutian",	// fb_tzid_us_aleutian - 64921
	"US/Arizona",	// fb_tzid_us_arizona - 64920
	"US/Central",	// fb_tzid_us_central - 64919
	"US/East-Indiana",	// fb_tzid_us_east_indiana - 64918
	"US/Eastern",	// fb_tzid_us_eastern - 64917
	"US/Hawaii",	// fb_tzid_us_hawaii - 64916
	"US/Indiana-Starke",	// fb_tzid_us_indiana_starke - 64915
	"US/Michigan",	// fb_tzid_us_michigan - 64914
	"US/Mountain",	// fb_tzid_us_mountain - 64913
	"US/Pacific",	// fb_tzid_us_pacific - 64912
	"US/Pacific-New",	// fb_tzid_us_pacific_new - 64911
	"US/Samoa",	// fb_tzid_us_samoa - 64910
	"UTC",	// fb_tzid_utc - 64909
	"Universal",	// fb_tzid_universal - 64908
	"VST",	// fb_tzid_vst - 64907
	"W-SU",	// fb_tzid_w_su - 64906
	"WET",	// fb_tzid_wet - 64905
	"Zulu",	// fb_tzid_zulu - 64904
	"America/Nuuk",	// fb_tzid_america_nuuk - 64903
	"Asia/Qostanay",	// fb_tzid_asia_qostanay - 64902
	"Pacific/Kanton",	// fb_tzid_pacific_kanton - 64901
	"Europe/Kyiv",	// fb_tzid_europe_kyiv - 64900
	"America/Ciudad_Juarez"	// fb_tzid_america_ciudad_juarez - 64899
};
