7/27/2002

SUMMARY
-------

This example demonstrates how to create a DLL that will utilize the 
Flexible API from FLEXnet Licensing in order to access to TRL capibilities in 
Visual Basic or Delphi. This demonstration must be compiled with a 
C compiler and with your company's Vendor Keys and Encryption Seeds.

To Use
------

This demo library is used in conjunction with the vb_dll_client visual basic
project. The DLL and a TRL licnese file must be located in the same directory
as the vb_dll_client.exe example program.

Requirements
------------

  Microsoft Visual C++ 5.0 or greater
  Microsoft Visual Basic 6.0 or greater
  FLEXnet Licensing toolkit v8.0d or greater


To Build and Use the DLL
------------------------

(1) You must build the FLEXnet Licensing kit using a C compiler. This assumes you have
modified the lm_code.h with you vendor codes and CRO keys to match
the keys issued to you by Macrovision Corporation.
(2) Configure the vb_dll project to where it can find the FLEXnet Licensing libs and
header files.
(3) Build the vb_dll project.
(4) Copy the resulting DLL to the root directory of the vb_dll_client 
Visual Basic project.
(5) Create an EXE from the vb_dll_client project.
(6) Generate a TRL based license from the FLEXnet Licensing toolkit and copy the licnese
file to the root directory of vb_dll_client project.


FILES LIST
----------

vb_dll folder

  vb_dll.c 	- source for DLL skeleton code
  vb_dll.h	- header file for DLL skeleton code
  vb_dll.def 	- exported functions declaration
  Readme.txt    - This file

vb_dll_client folder

  vb_dll_client.frm    - Source for VB client Dialog 
  vb_dll_client.vbp    - VB project file
  vb_dll_client.vbw    - VB Workspace file
  vb_dll_interface.bas - Source for DLL interfacing for client dialog

Support files for vb_dll project

  lmgr.lib 	- provided in the FLEXnet Licensing toolkit
  lm_attr.h 	- provided in the FLEXnet Licensing toolkit
  lmclient.h 	- provided in the FLEXnet Licensing toolkit
  libcrvs.lib 	- provided in the FLEXnet Licensing toolkit
  libsb.lib 	- provided in the FLEXnet Licensing toolkit
  lmgr.lib 	- provided in the FLEXnet Licensing toolkit
  lm_new.obj 	- generated by when toolkit is built

NOTES
-----

  lm_new.obj must be generated before the creation of the DLL can 
  proceed. This file is critical to the security of your seeds and 
  TRL keys. Do not distribute this file with your application.
  See the FLEXnet Licensing Programming and Reference Guide for 
  more information.

  Demo last built with FLEXnet Licensing v8.1a.

