/*
  FILE GENERATED BY src/misc/writeBuildNum.sh
               *** DO NOT EDIT ***
  TO CHANGE ANY INFORMATION IN HERE PLEASE
  EDIT src/misc/writeBuildNum.sh
  FORMAL BUILD NUMBER:1613
*/

#define PRODUCT_VER_STRING "5.0.2.1613"
#define FILE_VER_STRING "WI-V5.0.2.1613"
#define LICENSE_VER_STRING "WI-V5.0.2.1613"
#define FILE_VER_NUMBER 5, 0, 2, 1613
#define FB_MAJOR_VER "5"
#define FB_MINOR_VER "0"
#define FB_REV_NO "2"
#define FB_BUILD_NO "1613"
#define FB_BUILD_TYPE "V"
#define FB_BUILD_SUFFIX "Firebird 5.0"
