/*
  FILE GENERATED BY src/misc/writeBuildNum.sh
               *** DO NOT EDIT ***
  TO CHANGE ANY INFORMATION IN HERE PLEASE
  EDIT src/misc/writeBuildNum.sh
  FORMAL BUILD NUMBER:27050
*/

#define PRODUCT_VER_STRING "2.5.7.27050"
#define FILE_VER_STRING "WI-V2.5.7.27050"
#define LICENSE_VER_STRING "WI-V2.5.7.27050"
#define FILE_VER_NUMBER 2, 5, 7, 27050
#define FB_MAJOR_VER "2"
#define FB_MINOR_VER "5"
#define FB_REV_NO "7"
#define FB_BUILD_NO "27050"
#define FB_BUILD_TYPE "V"
#define FB_BUILD_SUFFIX "Firebird 2.5"
