TOP_DIR = ../..

## includes

include $(TOP_DIR)/config.mk


## CPPFLAGS

CPPFLAGS += -I$(SRC_DIR)  # aqua_config.h


## CXXFLAGS

CXXFLAGS += -fpic


## main rules

all: $(OBJ)


## (dirs/dep/objects/clean/phony) rules

include $(TOP_DIR)/config_rules.mk
