matrix:
  fast_finish: true
  allow_failures:
    - os: osx
  include:
    # QT4 based build with Python 2.7 // using container based builds and prebuild binary dependencies in osgeo4travis
    - os: linux
      language: cpp
      env:
        - BUILD=qt4
        - QT_VERSION=4
#        - LLVM_VERSION=3.8
      sudo: false
      cache:
        apt: true
        directories:
          - $HOME/.ccache
      compiler: gcc
      addons:
        postgresql: "9.4"
        apt:
          sources:
#            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports # doxygen 1.8.3
          packages:
            - bison
            - gcc-6
            - g++-6
            - doxygen
            - flex
            - flip
            - libfcgi-dev
            - libfftw3-3
            - libpq-dev
            - libqscintilla2-dev
            - libqt4-dev
            - libqt4-opengl-dev
            - libqt4-sql-sqlite
            - libqtwebkit-dev
            - libqwt-dev
            - libspatialindex-dev
            - libspatialite-dev
            - libsqlite3-dev
            - pkg-config
            - poppler-utils
            - pyqt4-dev-tools
            - python
            - python-dev
            - python-numpy
            - python-pip
            - python-psycopg2
            - python-qscintilla2
            - python-qt4-dev
            - python-qt4-sql
            - python-sip
            - python-sip-dev
            - txt2tags
            - xvfb
    # QT5 based build with Python 3 // using container based builds and prebuild binary dependencies in osgeo4travis
    - os: linux
      language: python # This lets us use newer python versions from virtualenv
      env:
        - BUILD=qt5
        - QT_VERSION=5
        - LLVM_VERSION=3.8
      sudo: false
      cache:
        apt: true
        directories:
          - $HOME/.ccache
      compiler: gcc
      python: "3.3"
      addons:
        postgresql: "9.4"
        apt:
          sources:
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports # doxygen 1.8.3
          packages:
            - doxygen
            - bison
            - flex
            - graphviz
            - libpq-dev
            - libfcgi-dev
            - libfftw3-3	    
            - pkg-config
            - poppler-utils
            - txt2tags
            - xvfb
            - flip
            - clang-3.8
    # OSX based build with QT4 and Python 2
    - os: osx
      env:
        - BUILD=osx
        - IGNORE_BUILD_FAILURES=YES

git:
  depth: 30

notifications:
  irc: "chat.freenode.net#qgis-test"
  on_failure: change
  on_success: change
  skip_join: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/467e3aff72e344d1dae3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: never # default: never

before_install:
  - ./ci/travis/${TRAVIS_OS_NAME}/before_install.sh

install:
  - ./ci/travis/${TRAVIS_OS_NAME}/install.sh

before_script:
  - ./ci/travis/${TRAVIS_OS_NAME}/before_script.sh

script:
  - ./ci/travis/${TRAVIS_OS_NAME}/script.sh

after_script:
  - ./ci/travis/${TRAVIS_OS_NAME}/after_script.sh
