TOPDIR = ../../.
include $(TOPDIR)/Make/makedefs 

C++FILES =\
	ThreadObserver.cpp \
	ThreadReporter.cpp \
	SimpleThreader.cpp \
	$(NULL)

INC      += -I$(TOPDIR)/include
LIBS     += -lOpenThreadPThread

EXEC = SimpleThreader

include $(TOPDIR)/Make/makerules