copy c:\Surge\DigitalGlobe\tools\src\GDAL\alg\gdalgrid.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\alg\gdalgrid_priv.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\alg\gdalwarper.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\alg\gdalwarpkernel_opencl.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\alg\gdal_alg.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\alg\gdal_alg_priv.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\alg\gdal_simplesurf.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\alg\gvgcpfit.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\alg\thinplatespline.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\apps\commonutils.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\bridge\gdalbridge.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\aigrid\aigrid.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\blx\blx.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\bsb\bsb_read.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\ceos\ceosopen.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\ceos2\ceos.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\dted\dted_api.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\e00grid\e00compr.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\ecw\gdal_ecw.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\envisat\EnvisatFile.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\envisat\records.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\ers\ershdrnode.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\fit\fit.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\fit\gstEndian.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\fit\gstTypes.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\georaster\georaster_priv.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\georaster\oci_wrapper.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gif\gifabstractdataset.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gif\giflib\gif_hash.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gif\giflib\gif_lib.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gif\giflib\gif_lib_private.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\grib\degrib18\degrib\clock.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\grib\degrib18\degrib\datasource.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\grib\degrib18\degrib\degrib1.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\grib\degrib18\degrib\degrib2.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\grib\degrib18\degrib\engribapi.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\grib\degrib18\degrib\filedatasource.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\grib\degrib18\degrib\fileendian.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\grib\degrib18\degrib\grib2api.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\grib\degrib18\degrib\inventory.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\grib\degrib18\degrib\memendian.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\grib\degrib18\degrib\memorydatasource.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\grib\degrib18\degrib\meta.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\grib\degrib18\degrib\metaname.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\grib\degrib18\degrib\myassert.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\grib\degrib18\degrib\myerror.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\grib\degrib18\degrib\myutil.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\grib\degrib18\degrib\scan.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\grib\degrib18\degrib\tdlpack.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\grib\degrib18\degrib\type.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\grib\degrib18\degrib\weather.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\grib\degrib18\g2clib-1.0.4\drstemplates.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\grib\degrib18\g2clib-1.0.4\grib2.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\grib\degrib18\g2clib-1.0.4\gridtemplates.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\grib\degrib18\g2clib-1.0.4\pdstemplates.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gtiff\gtiff.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gtiff\gt_citation.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gtiff\gt_jpeg_copy.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gtiff\gt_overview.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gtiff\gt_wkt_srs.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gtiff\gt_wkt_srs_for_gdal.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gtiff\tifvsi.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gtiff\tif_float.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gtiff\libgeotiff\cpl_serv.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gtiff\libgeotiff\gdal_libgeotiff_symbol_rename.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gtiff\libgeotiff\geokeys.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gtiff\libgeotiff\geonames.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gtiff\libgeotiff\geotiff.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gtiff\libgeotiff\geotiffio.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gtiff\libgeotiff\geovalues.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gtiff\libgeotiff\geo_config.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gtiff\libgeotiff\geo_keyp.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gtiff\libgeotiff\geo_normalize.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gtiff\libgeotiff\geo_simpletags.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gtiff\libgeotiff\geo_tiffp.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gtiff\libgeotiff\xtiffio.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gtiff\libtiff\gdal_libtiff_symbol_rename.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gtiff\libtiff\t4.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gtiff\libtiff\tiff.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gtiff\libtiff\tiffconf.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gtiff\libtiff\tiffio.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gtiff\libtiff\tiffiop.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gtiff\libtiff\tiffvers.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gtiff\libtiff\tif_config.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gtiff\libtiff\tif_dir.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gtiff\libtiff\tif_fax3.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gtiff\libtiff\tif_predict.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gtiff\libtiff\uvcode.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\gxf\gxfopen.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\hdf4\hdf4compat.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\hdf4\hdf4dataset.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\hdf4\hdf-eos\ease.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\hdf4\hdf-eos\HdfEosDef.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\hdf4\hdf-eos\HDFEOSVersion.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\hdf5\gh5_convenience.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\hdf5\hdf5dataset.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\hfa\hfa.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\hfa\hfa_p.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\idrisi\idrisi.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\ilwis\ilwisdataset.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\ingr\IngrTypes.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\ingr\IntergraphBand.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\ingr\IntergraphDataset.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\ingr\JpegHelper.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\iso8211\iso8211.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\jp2kak\subfile_source.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\jp2kak\vsil_target.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\jpeg\vsidataio.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\jpeg\libjpeg\jchuff.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\jpeg\libjpeg\jconfig.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\jpeg\libjpeg\jdct.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\jpeg\libjpeg\jdhuff.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\jpeg\libjpeg\jerror.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\jpeg\libjpeg\jinclude.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\jpeg\libjpeg\jmemsys.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\jpeg\libjpeg\jmorecfg.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\jpeg\libjpeg\jpegint.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\jpeg\libjpeg\jpeglib.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\jpeg\libjpeg\jversion.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\jpeg2000\jpeg2000_vsil_io.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\jpipkak\jpipkakdataset.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\kmlsuperoverlay\kmlsuperoverlaydataset.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\mem\memdataset.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\mrsid\mrsidstream.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\msg\msgcommand.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\msg\msgdataset.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\msg\prologue.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\msg\reflectancecalculator.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\msg\xritheaderparser.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\msgn\msg_basic_types.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\msgn\msg_reader_core.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\netcdf\netcdfdataset.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\nitf\mgrs.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\nitf\nitfdataset.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\nitf\nitflib.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\nitf\rpftoclib.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\northwood\northwood.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\gdal_pcidsk.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\pcidsk.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\pcidsk_ads40.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\pcidsk_airphoto.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\pcidsk_array.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\pcidsk_binary.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\pcidsk_buffer.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\pcidsk_channel.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\pcidsk_config.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\pcidsk_edb.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\pcidsk_ephemeris.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\pcidsk_exception.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\pcidsk_file.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\pcidsk_gcp.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\pcidsk_gcpsegment.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\pcidsk_georef.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\pcidsk_interfaces.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\pcidsk_io.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\pcidsk_mutex.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\pcidsk_pct.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\pcidsk_poly.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\pcidsk_rpc.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\pcidsk_segment.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\pcidsk_shape.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\pcidsk_tex.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\pcidsk_toutin.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\pcidsk_types.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\pcidsk_vectorsegment.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\channel\cbandinterleavedchannel.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\channel\cexternalchannel.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\channel\cpcidskchannel.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\channel\cpixelinterleavedchannel.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\channel\ctiledchannel.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\core\clinksegment.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\core\cpcidskfile.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\core\metadataset.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\core\mutexholder.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\core\pcidsk_utils.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\core\protectedfile.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\core\sysvirtualfile.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\segment\cpcidskads40model.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\segment\cpcidskapmodel.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\segment\cpcidskbinarysegment.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\segment\cpcidskbitmap.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\segment\cpcidskephemerissegment.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\segment\cpcidskgcp2segment.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\segment\cpcidskgeoref.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\segment\cpcidskpct.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\segment\cpcidskpolymodel.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\segment\cpcidskrpcmodel.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\segment\cpcidsksegment.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\segment\cpcidsktoutinmodel.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\segment\cpcidskvectorsegment.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\segment\cpcidsk_array.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\segment\cpcidsk_tex.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\segment\metadatasegment.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\segment\orbitstructures.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\segment\pcidsksegmentbuilder.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\segment\sysblockmap.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\segment\toutinstructures.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\segment\vecsegdataindex.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcidsk\sdk\segment\vecsegheader.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcraster\pcrasterdataset.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcraster\pcrasterrasterband.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcraster\pcrasterutil.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcraster\libcsf\csf.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcraster\libcsf\csfattr.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcraster\libcsf\csfimpl.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcraster\libcsf\csftypes.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pcraster\libcsf\pcrtypes.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pdf\pdfcreatecopy.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pdf\pdfdataset.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pdf\pdfio.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pdf\pdfobject.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pds\nasakeywordhandler.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\pgchip\pgchip.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\png\libpng\png.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\png\libpng\pngconf.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\postgisraster\postgisraster.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\rasdaman\rasdamandataset.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\rasterlite\rasterlitedataset.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\raw\atlsci_spheroid.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\raw\rawdataset.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\rmf\rmfdataset.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\sde\gdal_sde.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\sde\sdedataset.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\sde\sdeerror.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\sde\sderasterband.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\sdts\sdts_al.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\vrt\gdal_vrt.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\vrt\vrtdataset.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\wms\gdalhttp.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\wms\md5.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\wms\minidriver_tiled_wms.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\wms\minidriver_tileservice.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\wms\minidriver_tms.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\wms\minidriver_virtualearth.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\wms\minidriver_wms.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\wms\minidriver_worldwind.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\wms\wmsdriver.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\wms\wmsmetadataset.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\zlib\crc32.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\zlib\deflate.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\zlib\inffast.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\zlib\inffixed.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\zlib\inflate.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\zlib\inftrees.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\zlib\trees.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\zlib\zconf.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\zlib\zlib.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\frmts\zlib\zutil.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\gcore\gdal.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\gcore\gdalexif.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\gcore\gdalgeorefpamdataset.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\gcore\gdaljp2abstractdataset.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\gcore\gdaljp2metadata.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\gcore\gdal_frmts.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\gcore\gdal_pam.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\gcore\gdal_priv.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\gcore\gdal_proxy.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\gcore\gdal_rat.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\gcore\gdal_version.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrgeomediageometry.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrpgeogeometry.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogr_api.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogr_core.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogr_expat.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogr_feature.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogr_featurestyle.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogr_geocoding.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogr_geometry.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogr_geos.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogr_p.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogr_spatialref.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogr_srs_api.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogr_srs_esri_names.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\osr_cs_wkt.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\osr_cs_wkt_parser.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\swq.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\ogrsf_frmts.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\ogr_attrind.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\aeronavfaa\ogr_aeronavfaa.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\arcgen\ogr_arcgen.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\arcobjects\aoutils.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\arcobjects\ogr_ao.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\avc\avc.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\avc\avc_mbyte.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\avc\dbfopen.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\avc\ogr_avc.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\bna\ogrbnaparser.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\bna\ogr_bna.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\cartodb\ogr_cartodb.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\couchdb\ogr_couchdb.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\csv\ogr_csv.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\dgn\dgnlib.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\dgn\dgnlibp.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\dgn\ogr_dgn.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\dgn\dist\cpl_config.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\dods\ogr_dods.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\dwg\ogr_dwg.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\dxf\ogrdxf_polyline_smooth.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\dxf\ogr_autocad_services.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\dxf\ogr_dxf.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\edigeo\ogr_edigeo.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\elastic\ogr_elastic.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\filegdb\FGdbUtils.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\filegdb\ogr_fgdb.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\fme\fme2ogr.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\generic\ogrlayerdecorator.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\generic\ogrlayerpool.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\generic\ogrmutexeddatasource.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\generic\ogrmutexedlayer.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\generic\ogrunionlayer.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\generic\ogrwarpedlayer.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\generic\ogr_gensql.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\geoconcept\geoconcept.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\geoconcept\geoconcept_syscoord.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\geoconcept\ogrgeoconceptdatasource.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\geoconcept\ogrgeoconceptdriver.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\geoconcept\ogrgeoconceptlayer.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\geojson\ogrgeojsonreader.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\geojson\ogrgeojsonutils.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\geojson\ogrgeojsonwriter.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\geojson\ogr_geojson.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\geojson\libjson\arraylist.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\geojson\libjson\bits.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\geojson\libjson\config.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\geojson\libjson\debug.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\geojson\libjson\json.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\geojson\libjson\json_config.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\geojson\libjson\json_c_version.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\geojson\libjson\json_inttypes.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\geojson\libjson\json_object.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\geojson\libjson\json_object_iterator.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\geojson\libjson\json_object_private.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\geojson\libjson\json_tokener.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\geojson\libjson\json_util.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\geojson\libjson\linkhash.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\geojson\libjson\printbuf.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\geojson\libjson\symbol_renames.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\geomedia\ogr_geomedia.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\georss\ogr_georss.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\gft\ogr_gft.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\gml\gmlreader.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\gml\gmlreaderp.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\gml\gmlregistry.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\gml\gmlutils.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\gml\ogr_gml.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\gml\parsexsd.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\gmt\ogr_gmt.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\gpkg\ogrgeopackageutility.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\gpkg\ogr_geopackage.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\gpsbabel\ogr_gpsbabel.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\gpx\ogr_gpx.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\grass\ogrgrass.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\gtm\gtm.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\gtm\ogr_gtm.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\htf\ogr_htf.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\idb\ogr_idb.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\idrisi\ogr_idrisi.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\ili\ili1reader.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\ili\ili1readerp.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\ili\ili2reader.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\ili\ili2readerp.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\ili\ilihelper.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\ili\imdreader.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\ili\ogr_ili1.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\ili\ogr_ili2.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\ingres\ogr_ingres.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\kml\kml.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\kml\kmlnode.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\kml\kmlutility.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\kml\kmlvector.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\kml\ogr_kml.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\libkml\ogrlibkmlfeature.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\libkml\ogrlibkmlfeaturestyle.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\libkml\ogrlibkmlfield.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\libkml\ogrlibkmlgeometry.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\libkml\ogrlibkmlstyle.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\libkml\ogr_libkml.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\mdb\ogr_mdb.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\mem\ogr_mem.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\mitab\mitab.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\mitab\mitab_geometry.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\mitab\mitab_ogr_driver.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\mitab\mitab_priv.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\mitab\mitab_utils.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\mssqlspatial\ogr_mssqlspatial.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\mysql\ogr_mysql.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\nas\nasreaderp.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\nas\ogr_nas.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\ntf\ntf.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\oci\ogr_oci.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\odbc\ogr_odbc.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\ods\ods_formula.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\ods\ogr_ods.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\ogdi\ogrogdi.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\openair\ogr_openair.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\openfilegdb\filegdbtable.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\openfilegdb\filegdbtable_priv.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\openfilegdb\ogr_openfilegdb.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\osm\gpb.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\osm\ogr_osm.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\osm\osm_parser.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\pcidsk\ogr_pcidsk.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\pdf\ogr_pdf.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\pds\ogr_pds.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\pg\ogrpgutility.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\pg\ogr_pg.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\pgdump\ogr_pgdump.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\pgeo\ogr_pgeo.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\rec\ogr_rec.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\s57\ogr_s57.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\s57\s57.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\s57\s57tables.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\sde\ogr_sde.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\sdts\ogr_sdts.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\segukooa\ogr_segukooa.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\segy\ogr_segy.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\shape\ogrshape.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\shape\shapefil.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\shape\shp_vsi.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\sosi\ogr_sosi.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\sqlite\ogrsqlite3ext.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\sqlite\ogrsqliteexecutesql.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\sqlite\ogrsqliteregexp.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\sqlite\ogrsqlitesqlfunctions.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\sqlite\ogrsqlitevirtualogr.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\sqlite\ogr_sqlite.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\sua\ogr_sua.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\svg\ogr_svg.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\sxf\ogr_sxf.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\sxf\org_sxf_defs.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\tiger\ogr_tiger.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\vfk\ogr_vfk.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\vfk\vfkreader.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\vfk\vfkreaderp.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\vrt\ogr_vrt.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\walk\ogis_geometry_wkb_struct.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\walk\ogrwalk.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\wasp\ogrwasp.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\wfs\ogr_wfs.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\xls\ogr_xls.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\xlsx\ogr_xlsx.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\xplane\ogr_xplane.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\xplane\ogr_xplane_apt_reader.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\xplane\ogr_xplane_awy_reader.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\xplane\ogr_xplane_fix_reader.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\xplane\ogr_xplane_geo_utils.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\xplane\ogr_xplane_nav_reader.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\ogr\ogrsf_frmts\xplane\ogr_xplane_reader.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\port\cplkeywordparser.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\port\cpl_atomic_ops.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\port\cpl_config.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\port\cpl_config_extras.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\port\cpl_conv.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\port\cpl_csv.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\port\cpl_error.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\port\cpl_hash_set.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\port\cpl_http.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\port\cpl_list.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\port\cpl_minixml.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\port\cpl_minizip_ioapi.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\port\cpl_minizip_unzip.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\port\cpl_minizip_zip.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\port\cpl_multiproc.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\port\cpl_odbc.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\port\cpl_port.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\port\cpl_progress.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\port\cpl_quad_tree.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\port\cpl_spawn.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\port\cpl_string.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\port\cpl_time.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\port\cpl_virtualmem.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\port\cpl_vsi.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\port\cpl_vsil_curl_priv.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\port\cpl_vsi_virtual.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\port\cpl_win32ce_api.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\port\cpl_wince.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\port\gdal_csv.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\swig\php\php_gdal.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\swig\php\php_gdalconst.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\swig\php\php_ogr.h D:\DG\tools\x86_64\gdal\include\gdal
copy c:\Surge\DigitalGlobe\tools\src\GDAL\swig\php\php_osr.h D:\DG\tools\x86_64\gdal\include\gdal
