# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.39
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_kmlengine', [dirname(__file__)])
        except ImportError:
            import _kmlengine
            return _kmlengine
        if fp is not None:
            try:
                _mod = imp.load_module('_kmlengine', fp, pathname, description)
            finally:
                fp.close()
                return _mod
    _kmlengine = swig_import_helper()
    del swig_import_helper
else:
    import _kmlengine
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


import kmldom
import kmlbase
class Bbox(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Bbox, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Bbox, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _kmlengine.new_Bbox(*args)
        try: self.this.append(this)
        except: self.this = this
    def Contains(self, *args): return _kmlengine.Bbox_Contains(self, *args)
    def ExpandFromBbox(self, *args): return _kmlengine.Bbox_ExpandFromBbox(self, *args)
    def ExpandLatitude(self, *args): return _kmlengine.Bbox_ExpandLatitude(self, *args)
    def ExpandLongitude(self, *args): return _kmlengine.Bbox_ExpandLongitude(self, *args)
    def ExpandLatLon(self, *args): return _kmlengine.Bbox_ExpandLatLon(self, *args)
    def get_north(self): return _kmlengine.Bbox_get_north(self)
    def get_south(self): return _kmlengine.Bbox_get_south(self)
    def get_east(self): return _kmlengine.Bbox_get_east(self)
    def get_west(self): return _kmlengine.Bbox_get_west(self)
    __swig_destroy__ = _kmlengine.delete_Bbox
    __del__ = lambda self : None;
Bbox_swigregister = _kmlengine.Bbox_swigregister
Bbox_swigregister(Bbox)


def Clone(*args):
  return _kmlengine.Clone(*args)
Clone = _kmlengine.Clone

def GetFeatureBounds(*args):
  return _kmlengine.GetFeatureBounds(*args)
GetFeatureBounds = _kmlengine.GetFeatureBounds

def GetFeatureLatLon(*args):
  return _kmlengine.GetFeatureLatLon(*args)
GetFeatureLatLon = _kmlengine.GetFeatureLatLon

def GetRootFeature(*args):
  return _kmlengine.GetRootFeature(*args)
GetRootFeature = _kmlengine.GetRootFeature
class KmlFile(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, KmlFile, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, KmlFile, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_getmethods__["CreateFromParse"] = lambda x: _kmlengine.KmlFile_CreateFromParse
    if _newclass:CreateFromParse = staticmethod(_kmlengine.KmlFile_CreateFromParse)
    __swig_getmethods__["CreateFromImport"] = lambda x: _kmlengine.KmlFile_CreateFromImport
    if _newclass:CreateFromImport = staticmethod(_kmlengine.KmlFile_CreateFromImport)
    def get_root(self): return _kmlengine.KmlFile_get_root(self)
    def SerializeToString(self): return _kmlengine.KmlFile_SerializeToString(self)
    def GetObjectById(self, *args): return _kmlengine.KmlFile_GetObjectById(self, *args)
    def GetSharedStyleById(self, *args): return _kmlengine.KmlFile_GetSharedStyleById(self, *args)
    __swig_destroy__ = _kmlengine.delete_KmlFile
    __del__ = lambda self : None;
KmlFile_swigregister = _kmlengine.KmlFile_swigregister
KmlFile_swigregister(KmlFile)

def KmlFile_CreateFromParse(*args):
  return _kmlengine.KmlFile_CreateFromParse(*args)
KmlFile_CreateFromParse = _kmlengine.KmlFile_CreateFromParse

def KmlFile_CreateFromImport(*args):
  return _kmlengine.KmlFile_CreateFromImport(*args)
KmlFile_CreateFromImport = _kmlengine.KmlFile_CreateFromImport

class KmzFile(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, KmzFile, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, KmzFile, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_getmethods__["OpenFromFile"] = lambda x: _kmlengine.KmzFile_OpenFromFile
    if _newclass:OpenFromFile = staticmethod(_kmlengine.KmzFile_OpenFromFile)
    __swig_getmethods__["CreateFromString"] = lambda x: _kmlengine.KmzFile_CreateFromString
    if _newclass:CreateFromString = staticmethod(_kmlengine.KmzFile_CreateFromString)
    def ReadKml(self): return _kmlengine.KmzFile_ReadKml(self)
    def ReadFile(self, *args): return _kmlengine.KmzFile_ReadFile(self, *args)
    __swig_destroy__ = _kmlengine.delete_KmzFile
    __del__ = lambda self : None;
KmzFile_swigregister = _kmlengine.KmzFile_swigregister
KmzFile_swigregister(KmzFile)

def KmzFile_OpenFromFile(*args):
  return _kmlengine.KmzFile_OpenFromFile(*args)
KmzFile_OpenFromFile = _kmlengine.KmzFile_OpenFromFile

def KmzFile_CreateFromString(*args):
  return _kmlengine.KmzFile_CreateFromString(*args)
KmzFile_CreateFromString = _kmlengine.KmzFile_CreateFromString


def KmzSplit(*args):
  return _kmlengine.KmzSplit(*args)
KmzSplit = _kmlengine.KmzSplit

def SplitUri(*args):
  return _kmlengine.SplitUri(*args)
SplitUri = _kmlengine.SplitUri


