/* This file was generated by syncqt. */
#ifndef QT_QTCANVAS3D_VERSION_H
#define QT_QTCANVAS3D_VERSION_H

#define QTCANVAS3D_VERSION_STR "5.7.0"

#define QTCANVAS3D_VERSION 0x050700

#endif // QT_QTCANVAS3D_VERSION_H
