# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.4
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pyossim', [dirname(__file__)])
        except ImportError:
            import _pyossim
            return _pyossim
        if fp is not None:
            try:
                _mod = imp.load_module('_pyossim', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _pyossim = swig_import_helper()
    del swig_import_helper
else:
    import _pyossim
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


OSSIM_VERTEX_ORDER_UNKNOWN = _pyossim.OSSIM_VERTEX_ORDER_UNKNOWN
OSSIM_CLOCKWISE_ORDER = _pyossim.OSSIM_CLOCKWISE_ORDER
OSSIM_COUNTERCLOCKWISE_ORDER = _pyossim.OSSIM_COUNTERCLOCKWISE_ORDER
OSSIM_HISTO_MODE_UNKNOWN = _pyossim.OSSIM_HISTO_MODE_UNKNOWN
OSSIM_HISTO_MODE_NORMAL = _pyossim.OSSIM_HISTO_MODE_NORMAL
OSSIM_HISTO_MODE_FAST = _pyossim.OSSIM_HISTO_MODE_FAST
OSSIM_PIXEL_IS_POINT = _pyossim.OSSIM_PIXEL_IS_POINT
OSSIM_PIXEL_IS_AREA = _pyossim.OSSIM_PIXEL_IS_AREA
OSSIM_SCALAR_UNKNOWN = _pyossim.OSSIM_SCALAR_UNKNOWN
OSSIM_UINT8 = _pyossim.OSSIM_UINT8
OSSIM_SINT8 = _pyossim.OSSIM_SINT8
OSSIM_UINT16 = _pyossim.OSSIM_UINT16
OSSIM_SINT16 = _pyossim.OSSIM_SINT16
OSSIM_UINT32 = _pyossim.OSSIM_UINT32
OSSIM_SINT32 = _pyossim.OSSIM_SINT32
OSSIM_FLOAT32 = _pyossim.OSSIM_FLOAT32
OSSIM_FLOAT64 = _pyossim.OSSIM_FLOAT64
OSSIM_CINT16 = _pyossim.OSSIM_CINT16
OSSIM_CINT32 = _pyossim.OSSIM_CINT32
OSSIM_CFLOAT32 = _pyossim.OSSIM_CFLOAT32
OSSIM_CFLOAT64 = _pyossim.OSSIM_CFLOAT64
OSSIM_UCHAR = _pyossim.OSSIM_UCHAR
OSSIM_USHORT16 = _pyossim.OSSIM_USHORT16
OSSIM_SSHORT16 = _pyossim.OSSIM_SSHORT16
OSSIM_USHORT11 = _pyossim.OSSIM_USHORT11
OSSIM_FLOAT = _pyossim.OSSIM_FLOAT
OSSIM_NORMALIZED_FLOAT = _pyossim.OSSIM_NORMALIZED_FLOAT
OSSIM_DOUBLE = _pyossim.OSSIM_DOUBLE
OSSIM_NORMALIZED_DOUBLE = _pyossim.OSSIM_NORMALIZED_DOUBLE
OSSIM_INTERLEAVE_UNKNOWN = _pyossim.OSSIM_INTERLEAVE_UNKNOWN
OSSIM_BIL = _pyossim.OSSIM_BIL
OSSIM_BIP = _pyossim.OSSIM_BIP
OSSIM_BSQ = _pyossim.OSSIM_BSQ
OSSIM_BSQ_MULTI_FILE = _pyossim.OSSIM_BSQ_MULTI_FILE
OSSIM_ORIGIN_LOCATION_UNKNOWN = _pyossim.OSSIM_ORIGIN_LOCATION_UNKNOWN
OSSIM_CENTER = _pyossim.OSSIM_CENTER
OSSIM_UPPER_LEFT = _pyossim.OSSIM_UPPER_LEFT
OSSIM_UPPER_LEFT_CENTER = _pyossim.OSSIM_UPPER_LEFT_CENTER
OSSIM_LOWER_LEFT = _pyossim.OSSIM_LOWER_LEFT
OSSIM_LOWER_LEFT_CENTER = _pyossim.OSSIM_LOWER_LEFT_CENTER
OSSIM_COORDINATE_SYSTEM_UNKNOWN = _pyossim.OSSIM_COORDINATE_SYSTEM_UNKNOWN
OSSIM_IMAGE_SPACE = _pyossim.OSSIM_IMAGE_SPACE
OSSIM_GEOGRAPHIC_SPACE = _pyossim.OSSIM_GEOGRAPHIC_SPACE
OSSIM_PROJECTED_SPACE = _pyossim.OSSIM_PROJECTED_SPACE
OSSIM_GEOCENTRIC_SPACE = _pyossim.OSSIM_GEOCENTRIC_SPACE
OSSIM_LEFT_HANDED = _pyossim.OSSIM_LEFT_HANDED
OSSIM_RIGHT_HANDED = _pyossim.OSSIM_RIGHT_HANDED
OSSIM_UNIT_UNKNOWN = _pyossim.OSSIM_UNIT_UNKNOWN
OSSIM_METERS = _pyossim.OSSIM_METERS
OSSIM_FEET = _pyossim.OSSIM_FEET
OSSIM_US_SURVEY_FEET = _pyossim.OSSIM_US_SURVEY_FEET
OSSIM_DEGREES = _pyossim.OSSIM_DEGREES
OSSIM_RADIANS = _pyossim.OSSIM_RADIANS
OSSIM_NAUTICAL_MILES = _pyossim.OSSIM_NAUTICAL_MILES
OSSIM_SECONDS = _pyossim.OSSIM_SECONDS
OSSIM_MINUTES = _pyossim.OSSIM_MINUTES
OSSIM_PIXEL = _pyossim.OSSIM_PIXEL
OSSIM_MILES = _pyossim.OSSIM_MILES
OSSIM_MILLIMETERS = _pyossim.OSSIM_MILLIMETERS
OSSIM_MICRONS = _pyossim.OSSIM_MICRONS
OSSIM_CENTIMETERS = _pyossim.OSSIM_CENTIMETERS
OSSIM_YARDS = _pyossim.OSSIM_YARDS
OSSIM_INCHES = _pyossim.OSSIM_INCHES
OSSIM_KILOMETERS = _pyossim.OSSIM_KILOMETERS
OSSIM_STATUS_UNKNOWN = _pyossim.OSSIM_STATUS_UNKNOWN
OSSIM_NULL = _pyossim.OSSIM_NULL
OSSIM_EMPTY = _pyossim.OSSIM_EMPTY
OSSIM_PARTIAL = _pyossim.OSSIM_PARTIAL
OSSIM_FULL = _pyossim.OSSIM_FULL
OSSIM_IMAGE_TYPE_UNKNOWN = _pyossim.OSSIM_IMAGE_TYPE_UNKNOWN
OSSIM_TIFF_STRIP = _pyossim.OSSIM_TIFF_STRIP
OSSIM_TIFF_STRIP_BAND_SEPARATE = _pyossim.OSSIM_TIFF_STRIP_BAND_SEPARATE
OSSIM_TIFF_TILED = _pyossim.OSSIM_TIFF_TILED
OSSIM_TIFF_TILED_BAND_SEPARATE = _pyossim.OSSIM_TIFF_TILED_BAND_SEPARATE
OSSIM_GENERAL_RASTER_BIP = _pyossim.OSSIM_GENERAL_RASTER_BIP
OSSIM_GENERAL_RASTER_BIL = _pyossim.OSSIM_GENERAL_RASTER_BIL
OSSIM_GENERAL_RASTER_BSQ = _pyossim.OSSIM_GENERAL_RASTER_BSQ
OSSIM_JPEG = _pyossim.OSSIM_JPEG
OSSIM_META_UNKNOWN = _pyossim.OSSIM_META_UNKNOWN
OSSIM_META_TFW = _pyossim.OSSIM_META_TFW
OSSIM_META_JGW = _pyossim.OSSIM_META_JGW
OSSIM_META_GEOM = _pyossim.OSSIM_META_GEOM
OSSIM_META_README = _pyossim.OSSIM_META_README
OSSIM_META_FGDC = _pyossim.OSSIM_META_FGDC
OSSIM_META_ENVI = _pyossim.OSSIM_META_ENVI
OSSIM_LITTLE_ENDIAN = _pyossim.OSSIM_LITTLE_ENDIAN
OSSIM_BIG_ENDIAN = _pyossim.OSSIM_BIG_ENDIAN
TIFFTAG_OSSIM_METADATA = _pyossim.TIFFTAG_OSSIM_METADATA
class ossimElevSource(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ossimElevSource, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ossimElevSource, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    def getHeightAboveMSL(self, *args): return _pyossim.ossimElevSource_getHeightAboveMSL(self, *args)
    def getHeightAboveEllipsoid(self, *args): return _pyossim.ossimElevSource_getHeightAboveEllipsoid(self, *args)
    def intersectRay(self, *args): return _pyossim.ossimElevSource_intersectRay(self, *args)
    def getMinHeightAboveMSL(self): return _pyossim.ossimElevSource_getMinHeightAboveMSL(self)
    def getMaxHeightAboveMSL(self): return _pyossim.ossimElevSource_getMaxHeightAboveMSL(self)
    def getNullHeightValue(self): return _pyossim.ossimElevSource_getNullHeightValue(self)
    def getSeaLevelValue(self): return _pyossim.ossimElevSource_getSeaLevelValue(self)
    def pointHasCoverage(self, *args): return _pyossim.ossimElevSource_pointHasCoverage(self, *args)
    def getMeanSpacingMeters(self): return _pyossim.ossimElevSource_getMeanSpacingMeters(self)
    def getAccuracyLE90(self, *args): return _pyossim.ossimElevSource_getAccuracyLE90(self, *args)
    def getAccuracyCE90(self, *args): return _pyossim.ossimElevSource_getAccuracyCE90(self, *args)
    def getBoundingGndRect(self): return _pyossim.ossimElevSource_getBoundingGndRect(self)
    def canConnectMyInputTo(self, *args): return _pyossim.ossimElevSource_canConnectMyInputTo(self, *args)
    def initialize(self): return _pyossim.ossimElevSource_initialize(self)
    def getComputeStatisticsFlag(self): return _pyossim.ossimElevSource_getComputeStatisticsFlag(self)
    def setComputeStatisticsFlag(self, *args): return _pyossim.ossimElevSource_setComputeStatisticsFlag(self, *args)
ossimElevSource_swigregister = _pyossim.ossimElevSource_swigregister
ossimElevSource_swigregister(ossimElevSource)

class ossimElevationDatabase(ossimElevSource):
    __swig_setmethods__ = {}
    for _s in [ossimElevSource]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ossimElevationDatabase, name, value)
    __swig_getmethods__ = {}
    for _s in [ossimElevSource]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, ossimElevationDatabase, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    def __set__(self, *args): return _pyossim.ossimElevationDatabase___set__(self, *args)
    def getMeanSpacingMeters(self): return _pyossim.ossimElevationDatabase_getMeanSpacingMeters(self)
    def setGeoid(self, *args): return _pyossim.ossimElevationDatabase_setGeoid(self, *args)
    def getGeoid(self): return _pyossim.ossimElevationDatabase_getGeoid(self)
    def const_ossimElevationDatabase_getGeoid(self): return _pyossim.ossimElevationDatabase_const_ossimElevationDatabase_getGeoid(self)
    def open(self, *args): return _pyossim.ossimElevationDatabase_open(self, *args)
    def getConnectionString(self): return _pyossim.ossimElevationDatabase_getConnectionString(self)
    def getOpenCellList(self, *args): return _pyossim.ossimElevationDatabase_getOpenCellList(self, *args)
    def loadState(self, *args): return _pyossim.ossimElevationDatabase_loadState(self, *args)
    def saveState(self, *args): return _pyossim.ossimElevationDatabase_saveState(self, *args)
ossimElevationDatabase_swigregister = _pyossim.ossimElevationDatabase_swigregister
ossimElevationDatabase_swigregister(ossimElevationDatabase)

class ossimElevationCellDatabase(ossimElevationDatabase):
    __swig_setmethods__ = {}
    for _s in [ossimElevationDatabase]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ossimElevationCellDatabase, name, value)
    __swig_getmethods__ = {}
    for _s in [ossimElevationDatabase]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, ossimElevationCellDatabase, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    def __set__(self, *args): return _pyossim.ossimElevationCellDatabase___set__(self, *args)
    def loadState(self, *args): return _pyossim.ossimElevationCellDatabase_loadState(self, *args)
    def saveState(self, *args): return _pyossim.ossimElevationCellDatabase_saveState(self, *args)
    def getMinOpenCells(self): return _pyossim.ossimElevationCellDatabase_getMinOpenCells(self)
    def getMaxOpenCells(self): return _pyossim.ossimElevationCellDatabase_getMaxOpenCells(self)
    def setMinMaxOpenCells(self, *args): return _pyossim.ossimElevationCellDatabase_setMinMaxOpenCells(self, *args)
    def getMemoryMapCellsFlag(self): return _pyossim.ossimElevationCellDatabase_getMemoryMapCellsFlag(self)
    def setMemoryMapCellsFlag(self, *args): return _pyossim.ossimElevationCellDatabase_setMemoryMapCellsFlag(self, *args)
    def getOpenCellList(self, *args): return _pyossim.ossimElevationCellDatabase_getOpenCellList(self, *args)
    def createId(self, *args): return _pyossim.ossimElevationCellDatabase_createId(self, *args)
    def getOrCreateCellHandler(self, *args): return _pyossim.ossimElevationCellDatabase_getOrCreateCellHandler(self, *args)
    __swig_destroy__ = _pyossim.delete_ossimElevationCellDatabase
    __del__ = lambda self : None;
ossimElevationCellDatabase_swigregister = _pyossim.ossimElevationCellDatabase_swigregister
ossimElevationCellDatabase_swigregister(ossimElevationCellDatabase)

# This file is compatible with both classic and new-style classes.


