TOPDIR = ../../.
include $(TOPDIR)/Make/makedefs 

C++FILES =\
	ThreadObserver.c++ \
	ThreadReporter.c++ \
	WorkCrew.c++ \
	$(NULL)

INC      += -I$(TOPDIR)/include -I.
LIBS     += -lOpenThreadPThread

EXEC = WorkCrew

include $(TOPDIR)/Make/makerules