#########################################################################
# Copyright (c) 2003-2007 Macrovision Europe Ltd. and/or Macrovision Corporation. All Rights Reserved.
#        This software has been provided pursuant to a License Agreement
#        containing restrictions on its use.  This software contains
#        valuable trade secrets and proprietary information of 
#        Macrovision Corporation and is protected by law.  It may 
#        not be copied or distributed in any form or medium, disclosed 
#        to third parties, reverse engineered or used in any manner not 
#        provided for in said License Agreement except with the prior 
#        written authorization from Macrovision Corporation.
##########################################################################
INCLUDE=../../machind
LIBDIR=../../alpha_u1


vdinfo:	vdinfo.c
	cc -I$(INCLUDE) vdinfo.c -L$(LIBDIR) -llmgr -o vdinfo 
	
